/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prestamos.ventanas;
 
import prestamos.datos.tbclientedatos;

/**
 *
 * @author Elisvan
 */
public class ventanaprincipal extends javax.swing.JFrame {
    
    tbclientedatos cliente;
    public ventanaprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mclientes = new javax.swing.JMenu();
        aggclientes = new javax.swing.JMenuItem();
        bcliente = new javax.swing.JMenuItem();
        ecliente = new javax.swing.JMenuItem();
        eliminarcliente = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        reportesc = new javax.swing.JMenu();
        menulistac = new javax.swing.JMenuItem();
        menuprestamos = new javax.swing.JMenu();
        nuevoprestamo = new javax.swing.JMenuItem();
        buscarprestamo = new javax.swing.JMenuItem();
        editarprestamo = new javax.swing.JMenuItem();
        eliminarprestamo = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menulistaprestamos = new javax.swing.JMenu();
        listaprestamos = new javax.swing.JMenuItem();
        menupagos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        listapagos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoc.jpg"))); // NOI18N
        mclientes.setText("Clientes");
        mclientes.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        aggclientes.setText("Agregar Cliente");
        aggclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggclientesActionPerformed(evt);
            }
        });
        mclientes.add(aggclientes);

        bcliente.setText("Buscar Cliente");
        bcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclienteActionPerformed(evt);
            }
        });
        mclientes.add(bcliente);

        ecliente.setText("Editar cliente");
        ecliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eclienteActionPerformed(evt);
            }
        });
        mclientes.add(ecliente);

        eliminarcliente.setText("Eliminar cliente");
        eliminarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarclienteActionPerformed(evt);
            }
        });
        mclientes.add(eliminarcliente);
        mclientes.add(jSeparator1);

        reportesc.setText("Reportes");

        menulistac.setText("Lista de clientes");
        menulistac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menulistacActionPerformed(evt);
            }
        });
        reportesc.add(menulistac);

        mclientes.add(reportesc);

        jMenuBar1.add(mclientes);

        menuprestamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoprest.jpg"))); // NOI18N
        menuprestamos.setText("Prestamos");
        menuprestamos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        nuevoprestamo.setText("Nuevo prestamo");
        nuevoprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoprestamoActionPerformed(evt);
            }
        });
        menuprestamos.add(nuevoprestamo);

        buscarprestamo.setText("Buscar prestamo");
        buscarprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarprestamoActionPerformed(evt);
            }
        });
        menuprestamos.add(buscarprestamo);

        editarprestamo.setText("Editar prestamo");
        editarprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarprestamoActionPerformed(evt);
            }
        });
        menuprestamos.add(editarprestamo);

        eliminarprestamo.setText("Eliminar prestamo");
        eliminarprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarprestamoActionPerformed(evt);
            }
        });
        menuprestamos.add(eliminarprestamo);
        menuprestamos.add(jSeparator2);

        menulistaprestamos.setText("Reporte prestamos");

        listaprestamos.setText("Lista prestamos");
        listaprestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaprestamosActionPerformed(evt);
            }
        });
        menulistaprestamos.add(listaprestamos);

        menuprestamos.add(menulistaprestamos);

        jMenuBar1.add(menuprestamos);

        menupagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconopagos.jpg"))); // NOI18N
        menupagos.setText("Pagos");
        menupagos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jMenuItem1.setText("Realizar pago");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menupagos.add(jMenuItem1);
        menupagos.add(jSeparator3);

        jMenu1.setText("Reporte pagos");

        listapagos.setText("Lista pagos");
        listapagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listapagosActionPerformed(evt);
            }
        });
        jMenu1.add(listapagos);

        menupagos.add(jMenu1);

        jMenuBar1.add(menupagos);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclienteActionPerformed
      ventanaclientes nventana = new ventanaclientes(new javax.swing.JFrame(),true);
       nventana.setResizable(false);
       nventana.getBaggcliente().setEnabled(false);
       nventana.getTfnombrec().setEditable(false);
       nventana.getTfapellidosc().setEditable(false);
       nventana.getTfdireccionc().setEditable(false);
       nventana.getTftelefonoc().setEditable(false);
       nventana.getBeditarcliente().setEnabled(false);
        nventana.setLocationRelativeTo(null);
        nventana.setTitle("Buscar Cliente");
        nventana.setVisible(true);
        
       
    }//GEN-LAST:event_bclienteActionPerformed

    private void eclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eclienteActionPerformed
       ventanaclientes nventana = new ventanaclientes(new javax.swing.JFrame(),true);
       nventana.setResizable(false);
       nventana.getBaggcliente().setEnabled(false);
       nventana.getTfnombrec().setEditable(false);
       nventana.getTfapellidosc().setEditable(false);
       nventana.getTfdireccionc().setEditable(false);
       nventana.getTftelefonoc().setEditable(false);
        nventana.setLocationRelativeTo(null);
        nventana.setTitle("Editar Cliente");
        nventana.setVisible(true);
        
       
    }//GEN-LAST:event_eclienteActionPerformed

    private void aggclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggclientesActionPerformed
     ventanaclientes nventana = new ventanaclientes(new javax.swing.JFrame(),true);
       nventana.setResizable(false);
       nventana.getBbuscarc().setEnabled(false);
       nventana.getBeditarcliente().setEnabled(false);
        nventana.setLocationRelativeTo(null);
        nventana.setTitle("Agregar Cliente");
        nventana.setVisible(true);
    }//GEN-LAST:event_aggclientesActionPerformed

    private void eliminarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarclienteActionPerformed
       ventanaclientes nventana = new ventanaclientes(new javax.swing.JFrame(),true);
       nventana.setResizable(false);
       nventana.getBaggcliente().setText("Eliminar");
       nventana.getTfnombrec().setEditable(false);
       nventana.getTfapellidosc().setEditable(false);
       nventana.getTfdireccionc().setEditable(false);
       nventana.getTftelefonoc().setEditable(false);
       nventana.getBeditarcliente().setEnabled(false);
        nventana.setLocationRelativeTo(null);
        nventana.setTitle("Eliminar Cliente");
        nventana.setVisible(true);
    }//GEN-LAST:event_eliminarclienteActionPerformed

    private void menulistacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menulistacActionPerformed
       ventanareportec vreportec = new ventanareportec();
       vreportec.setLocationRelativeTo(null);
       vreportec.setResizable(false);
       vreportec.setVisible(true);
    }//GEN-LAST:event_menulistacActionPerformed

    private void nuevoprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoprestamoActionPerformed
     ventanaprestamos vprest = new ventanaprestamos();
     vprest.getTfvalorcuota().setEditable(false);
     vprest.setResizable(false);
     vprest.setTitle("Nuevo prestamo");
     vprest.getTfcuotas().setEditable(false);
     vprest.getTfvalorprestamo().setEditable(false);
     vprest.getTfinteres().setEditable(false);
     vprest.getTfvalorcuota().setEditable(false);
     vprest.getFechaprestamo().setEnabled(false);
     vprest.setLocationRelativeTo(null);
     vprest.setVisible(true);
     
    }//GEN-LAST:event_nuevoprestamoActionPerformed

    private void buscarprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarprestamoActionPerformed
    ventanaprestamos vprest = new ventanaprestamos();
     vprest.getTfvalorcuota().setEditable(false);
     vprest.getTfcuotas().setEditable(false);
     vprest.getTfinteres().setEditable(false);
     vprest.getTfvalorprestamo().setEditable(false);
     vprest.getTfclienteprestamo().setEditable(false);
     vprest.getLbbcprestamo().setText("Buscar prestamo");
     vprest.getLbtituloprestamo().setText("Buscar prestamo");
     vprest.setTitle("Buscar prestamo");
     vprest.setResizable(false);
     vprest.setLocationRelativeTo(null);
     vprest.setVisible(true);
    }//GEN-LAST:event_buscarprestamoActionPerformed

    private void editarprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarprestamoActionPerformed
     ventanaprestamos veprest = new ventanaprestamos();
     veprest.getLbbcprestamo().setText("Buscar prestamo");
     veprest.getLbtituloprestamo().setText("Editar Prestamo");
     veprest.setResizable(false);
     veprest.setTitle("Editar prestamo");
     veprest.getTfclienteprestamo().setEditable(true);
     veprest.getTfvalorprestamo().setEditable(false);
     veprest.getTfvalorcuota().setEditable(false);
     veprest.getTfinteres().setEditable(false);
     veprest.getTfcuotas().setEditable(false);
     veprest.getFechaprestamo().setEnabled(false);
     veprest.setLocationRelativeTo(null);
     veprest.setVisible(true);
    }//GEN-LAST:event_editarprestamoActionPerformed

    private void eliminarprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarprestamoActionPerformed
       ventanaprestamos velimprest = new ventanaprestamos();
       velimprest.setResizable(false);
       velimprest.setLocationRelativeTo(null);
       velimprest.getLbbcprestamo().setText("Buscar prestamo");
       velimprest.setTitle("Eliminar prestamo");
       velimprest.getLbtituloprestamo().setText("Eliminar prestamo");
       velimprest.setVisible(true);
    }//GEN-LAST:event_eliminarprestamoActionPerformed

    private void listaprestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaprestamosActionPerformed
       ventanareporteprest vrprest = new ventanareporteprest();
       vrprest.setLocationRelativeTo(null);
       vrprest.setResizable(false);
       vrprest.setVisible(true);
    }//GEN-LAST:event_listaprestamosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
     ventanapagos vpagos = new ventanapagos();
        vpagos.setResizable(false);
        vpagos.setLocationRelativeTo(null);
        vpagos.getTfcuotaspagar().setEditable(false);
        vpagos.getBtaceptarp().setEnabled(false);
        vpagos.setTitle("Realizar pago");
        vpagos.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void listapagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listapagosActionPerformed
      ventanareportepagos vrpagos = new ventanareportepagos();
      vrpagos.setResizable(false);
      vrpagos.setLocationRelativeTo(null);
      vrpagos.setVisible(true);
    }//GEN-LAST:event_listapagosActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aggclientes;
    private javax.swing.JMenuItem bcliente;
    private javax.swing.JMenuItem buscarprestamo;
    private javax.swing.JMenuItem ecliente;
    private javax.swing.JMenuItem editarprestamo;
    private javax.swing.JMenuItem eliminarcliente;
    private javax.swing.JMenuItem eliminarprestamo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuItem listapagos;
    private javax.swing.JMenuItem listaprestamos;
    private javax.swing.JMenu mclientes;
    private javax.swing.JMenuItem menulistac;
    private javax.swing.JMenu menulistaprestamos;
    private javax.swing.JMenu menupagos;
    private javax.swing.JMenu menuprestamos;
    private javax.swing.JMenuItem nuevoprestamo;
    private javax.swing.JMenu reportesc;
    // End of variables declaration//GEN-END:variables
}
