/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prestamos.ventanas;

import com.toedter.calendar.JCalendar;
import com.toedter.calendar.JDateChooser;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import prestamos.controlador.TbclienteJpaController;
import prestamos.controlador.TbprestamoJpaController;
import prestamos.datos.tbclientedatos;
import prestamos.datos.tbprestamosdatos;
import prestamos.entity.Tbcliente;
import prestamos.entity.Tbprestamo;


/**
 *
 * @author Elisvan
 */
public class ventanaprestamos extends javax.swing.JFrame {

    Tbprestamo nuevoprestamo;
   
    
    
    public ventanaprestamos() {
        initComponents();
       
    }

    ventanaprestamos(JFrame jFrame, boolean b) {
        initComponents();

    }

    public JButton getBbuscarcprestamo() {
        return bbuscarcprestamo;
    }

    public void setBbuscarcprestamo(JButton bbuscarcprestamo) {
        this.bbuscarcprestamo = bbuscarcprestamo;
    }

    public JDateChooser getFechaprestamo() {
        return fechaprestamo;
    }

    public void setFechaprestamo(JDateChooser fechaprestamo) {
        this.fechaprestamo = fechaprestamo;
    }

    public JComboBox<String> getjComboBox1() {
        return cbtipoprestamo;
    }

    public void setjComboBox1(JComboBox<String> jComboBox1) {
        this.cbtipoprestamo = jComboBox1;
    }

    public JTextField getTfbcprestamo() {
        return tfbcprestamo;
    }

    public void setTfbcprestamo(JTextField tfbcprestamo) {
        this.tfbcprestamo = tfbcprestamo;
    }

    public JTextField getTfclienteprestamo() {
        return tfclienteprestamo;
    }

    public void setTfclienteprestamo(JTextField tfclienteprestamo) {
        this.tfclienteprestamo = tfclienteprestamo;
    }

    public JTextField getTfcuotas() {
        return tfcuotas;
    }

    public void setTfcuotas(JTextField tfcuotas) {
        this.tfcuotas = tfcuotas;
    }

    public JTextField getTfinteres() {
        return tfinteres;
    }

    public void setTfinteres(JTextField tfinteres) {
        this.tfinteres = tfinteres;
    }

    public JTextField getTfvalorcuota() {
        return tfvalorcuota;
    }

    public void setTfvalorcuota(JTextField tfvalorcuota) {
        this.tfvalorcuota = tfvalorcuota;
    }

    public JTextField getTfvalorprestamo() {
        return tfvalorprestamo;
    }

    public void setTfvalorprestamo(JTextField tfvalorprestamo) {
        this.tfvalorprestamo = tfvalorprestamo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbbcprestamo = new javax.swing.JLabel();
        tfbcprestamo = new javax.swing.JTextField();
        bbuscarcprestamo = new javax.swing.JButton();
        blimpiarprestamo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfclienteprestamo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfvalorprestamo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfcuotas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbtipoprestamo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tfinteres = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfvalorcuota = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fechaprestamo = new com.toedter.calendar.JDateChooser();
        lbtituloprestamo = new javax.swing.JLabel();
        baceptarp = new javax.swing.JButton();
        bcancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        lbbcprestamo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbbcprestamo.setText("Buscar Cliente");

        bbuscarcprestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconobuscar_opt (1).png"))); // NOI18N
        bbuscarcprestamo.setText("Buscar");
        bbuscarcprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbuscarcprestamoActionPerformed(evt);
            }
        });

        blimpiarprestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/images_opt.jpg"))); // NOI18N
        blimpiarprestamo.setText("Limpiar");
        blimpiarprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blimpiarprestamoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Nombre cliente:");

        tfclienteprestamo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tfclienteprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfclienteprestamoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Valor del prestamo:");

        tfvalorprestamo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfvalorprestamoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfvalorprestamoKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Numero de cuotas");

        tfcuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcuotasActionPerformed(evt);
            }
        });
        tfcuotas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfcuotasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfcuotasKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Tipo de prestamo:");

        cbtipoprestamo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diario\t", "Semanal\t", "Quincenal", "Mensual" }));
        cbtipoprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtipoprestamoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Tasa interes(%)");

        tfinteres.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tfinteresInputMethodTextChanged(evt);
            }
        });
        tfinteres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfinteresActionPerformed(evt);
            }
        });
        tfinteres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfinteresKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfinteresKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Valor cuota:");

        tfvalorcuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfvalorcuotaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Fecha prestamo:");

        fechaprestamo.setDateFormatString("yyyy/MM/d");

        lbtituloprestamo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbtituloprestamo.setText("Agregar prestamo");

        baceptarp.setText("Aceptar");
        baceptarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baceptarpActionPerformed(evt);
            }
        });

        bcancelar.setText("Cancelar");
        bcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbtituloprestamo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbbcprestamo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfbcprestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bbuscarcprestamo)
                                .addGap(26, 26, 26)
                                .addComponent(blimpiarprestamo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfclienteprestamo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfvalorprestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfinteres, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(baceptarp)
                                        .addGap(66, 66, 66)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(jLabel5))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(tfvalorcuota, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tfcuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbtipoprestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(fechaprestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(bcancelar)))))
                        .addGap(0, 48, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lbtituloprestamo)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbbcprestamo)
                    .addComponent(tfbcprestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bbuscarcprestamo)
                    .addComponent(blimpiarprestamo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfclienteprestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfvalorprestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfcuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cbtipoprestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(tfvalorcuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel6)
                        .addComponent(tfinteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fechaprestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bcancelar)
                    .addComponent(baceptarp))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfclienteprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfclienteprestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfclienteprestamoActionPerformed

    private void tfinteresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfinteresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfinteresActionPerformed

    private void tfvalorcuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfvalorcuotaActionPerformed

    }//GEN-LAST:event_tfvalorcuotaActionPerformed

    private void blimpiarprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blimpiarprestamoActionPerformed
           tfbcprestamo.setText(null);
           tfclienteprestamo.setText(null);
           tfinteres.setText(null);
           tfcuotas.setText(null);
           tfvalorcuota.setText(null);
           tfvalorprestamo.setText(null);
    }//GEN-LAST:event_blimpiarprestamoActionPerformed

    private void tfcuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcuotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcuotasActionPerformed

    private void cbtipoprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtipoprestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbtipoprestamoActionPerformed

    public JLabel getLbtituloprestamo() {
        return lbtituloprestamo;
    }

    public JComboBox<String> getCbtipoprestamo() {
        return cbtipoprestamo;
    }

    public JLabel getLbbcprestamo() {
        return lbbcprestamo;
    }

    public void setLbtituloprestamo(JLabel lbtituloprestamo) {
        this.lbtituloprestamo = lbtituloprestamo;
    }

    public void setCbtipoprestamo(JComboBox<String> cbtipoprestamo) {
        this.cbtipoprestamo = cbtipoprestamo;
    }

    private void bcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelarActionPerformed

        
        this.dispose();
    }//GEN-LAST:event_bcancelarActionPerformed

    public void setLbbcprestamo(JLabel lbbcprestamo) {
        this.lbbcprestamo = lbbcprestamo;
    }

    private void baceptarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baceptarpActionPerformed
      String titulo = this.getTitle();
      tbprestamosdatos npres =  new tbprestamosdatos();
      
      JCalendar fechavencerc = fechaprestamo.getJCalendar() ;
    
        switch (titulo) {
              case "Nuevo prestamo":
                    if (tfclienteprestamo.getText().isEmpty() || tfvalorprestamo.getText().isEmpty() || tfinteres.getText().isEmpty() || fechaprestamo.getDate().equals(null) || tfcuotas.getText().isEmpty() ) {
                      JOptionPane.showMessageDialog(this,"Digite todos los campos");
                  }else{ 
                        
                        
                        int tprestamo = cbtipoprestamo.getSelectedIndex();
                        
                        switch (tprestamo) {
                               case 0:
                                
                               Calendar fpres = fechaprestamo.getCalendar();
                               fpres.add(Calendar.DATE, 1); 
                             
                                  fechavencerc.setCalendar(fpres);
                          
                                break;
                                case 1:
                                            fpres = fechaprestamo.getCalendar();
                                             fpres.add(Calendar.DATE, 7); 
                                               fechavencerc.setCalendar(fpres);
                                
                                break;
                               case 2:
                                            fpres = fechaprestamo.getCalendar();
                                             fpres.add(Calendar.DATE, 15); 
                                               fechavencerc.setCalendar(fpres); 
                                
                                
                                break;
                               case 3:
                                            fpres = fechaprestamo.getCalendar();
                                             fpres.add(Calendar.DATE,30); 
                                               fechavencerc.setCalendar(fpres);
                                
                                
                                break;
                            default:
                               
                        }
                         if (fechavencerc!=null) {
                              npres.Agregarprestamo(tfclienteprestamo.getText(), Integer.parseInt(tfvalorprestamo.getText()), Integer.parseInt(tfcuotas.getText()),Integer.parseInt(tfinteres.getText()), cbtipoprestamo.getSelectedItem().toString(), Integer.parseInt(tfvalorcuota.getText()),fechaprestamo.getDate(), fechavencerc.getDate()  );
                             JOptionPane.showMessageDialog(this, npres.mensaje);
                            
           
                         }
                    
                    
                    
                    }
                  
                break;
                 case "Editar prestamo":
                     
                   if (tfclienteprestamo.getText().isEmpty() || tfvalorprestamo.getText().isEmpty() || tfinteres.getText().isEmpty() || fechaprestamo.getDate().equals(null) || tfcuotas.getText().isEmpty() ) {
                      JOptionPane.showMessageDialog(this,"Digite todos los campos");
                  }else{
                         
                           int cbprestamo = cbtipoprestamo.getSelectedIndex();
                        
                        switch (cbprestamo) {
                               case 0:
                                
                               Calendar fpres = fechaprestamo.getCalendar();
                               fpres.add(Calendar.DATE, 1); 
                             
                                  fechavencerc.setCalendar(fpres);
                          
                                break;
                                case 1:
                                            fpres = fechaprestamo.getCalendar();
                                             fpres.add(Calendar.DATE, 7); 
                                               fechavencerc.setCalendar(fpres);
                                
                                break;
                               case 2:
                                            fpres = fechaprestamo.getCalendar();
                                             fpres.add(Calendar.DATE, 15); 
                                               fechavencerc.setCalendar(fpres); 
                                
                                
                                break;
                               case 3:
                                            fpres = fechaprestamo.getCalendar();
                                             fpres.add(Calendar.DATE,30); 
                                               fechavencerc.setCalendar(fpres);
                                
                                
                                break;
                            default:
                               
                        }                    
                         
                         
                         
                         
                         
                         npres.Editarprestamo(nuevoprestamo.getCodigo(),nuevoprestamo.getNombrec(),Integer.parseInt(tfvalorprestamo.getText()), Integer.parseInt(tfcuotas.getText()),Integer.parseInt(tfinteres.getText()) ,cbtipoprestamo.getSelectedItem().toString(), Integer.parseInt(tfvalorcuota.getText()), fechaprestamo.getDate(), fechavencerc.getDate());
                          JOptionPane.showMessageDialog(this, npres.mensaje);
                   
                   }
                
                break;
                 case "Eliminar prestamo":
                     
                      try {
                        Integer codigop ;
                        codigop = new Integer( tfbcprestamo.getText());
                        npres.Eliminarprestamo(codigop);
                        JOptionPane.showMessageDialog(this, npres.mensaje);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, npres.mensaje );
                    }
                     
                     
                        
                
                break;
                 case "Buscar prestamo":
                     this.dispose();
                     
                break;
                
            default:
                throw new AssertionError();
        }
        

    }//GEN-LAST:event_baceptarpActionPerformed

    private void tfinteresInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tfinteresInputMethodTextChanged
        if (!tfcuotas.getText().isEmpty() && !tfvalorprestamo.getText().isEmpty()) {

            Integer ncuotas, valorprestamo, valorcuota, interes;
            interes = Integer.parseInt(tfinteres.getText());
            ncuotas = Integer.parseInt(tfcuotas.getText());
            valorprestamo = Integer.parseInt(tfvalorprestamo.getText());
            valorcuota = (valorprestamo * (interes / 100) + valorprestamo) / ncuotas;
            tfvalorcuota.setText(valorcuota.toString());
            evt.consume();
        }

    }//GEN-LAST:event_tfinteresInputMethodTextChanged

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged

    }//GEN-LAST:event_formWindowStateChanged

    private void tfinteresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfinteresKeyReleased
       valorcuotas();
    }//GEN-LAST:event_tfinteresKeyReleased

    private void tfinteresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfinteresKeyTyped
        char c = evt.getKeyChar();
            if (c < '0' || c > '9') {
                evt.consume();
               JOptionPane.showMessageDialog(this, "Digite solo numeros");
        }

    }//GEN-LAST:event_tfinteresKeyTyped

    private void tfcuotasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcuotasKeyReleased
       valorcuotas();
    }//GEN-LAST:event_tfcuotasKeyReleased

    private void tfvalorprestamoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfvalorprestamoKeyReleased
     valorcuotas();
    }//GEN-LAST:event_tfvalorprestamoKeyReleased

    private void bbuscarcprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbuscarcprestamoActionPerformed
        String titulo = getTitle();

        tbprestamosdatos tbpres = new tbprestamosdatos();
            try {
                switch (titulo) {
                    case "Buscar prestamo":
                        String codigoprestamo = tfbcprestamo.getText();
                        if (codigoprestamo.isEmpty() == true) {
                                JOptionPane.showMessageDialog(this, "Digite el codigo del prestamo a buscar");
                        }else{
                                Integer codigopres = null;
                                codigopres = new Integer(codigoprestamo);
                                nuevoprestamo = tbpres.Buscarprestamo(codigopres);
                                if (nuevoprestamo == null) {
                                    JOptionPane.showMessageDialog(this, "El prestamo con codigo " + codigopres+ " no existe");
                            }else{
                                tfvalorprestamo.setText(String.valueOf(nuevoprestamo.getValorprestamo()));
                                tfcuotas.setText(String.valueOf(nuevoprestamo.getNcuotas()));
                                cbtipoprestamo.setSelectedItem(nuevoprestamo.getTipoprestamo());
                                tfinteres.setText(String.valueOf(nuevoprestamo.getInteres()));
                                fechaprestamo.setDate(nuevoprestamo.getFechaprestamo());
                                tfclienteprestamo.setText(nuevoprestamo.getNombrec());
                                valorcuotas();
                                }
                        }
                        
                        
               
                        break;
                    case "Editar prestamo":
                            String codigop = tfbcprestamo.getText();
                            if (codigop.isEmpty()==true) {
                               JOptionPane.showMessageDialog(this,"Digite el codigo del prestamo a buscar");
                        }else{
                                tbprestamosdatos tbpresta = new tbprestamosdatos();
                                Integer codigopres = Integer.parseInt(tfbcprestamo.getText());
                                nuevoprestamo = tbpresta.Buscarprestamo(codigopres);
                                if (nuevoprestamo == null) {
                                    JOptionPane.showMessageDialog(this,"El codigo del prestamo ingresado no existe");
                                    blimpiarprestamoActionPerformed(evt);
                                }else{
                                        tfvalorprestamo.setText(String.valueOf(nuevoprestamo.getValorprestamo()));
                                        tfcuotas.setText(String.valueOf(nuevoprestamo.getNcuotas()));
                                        cbtipoprestamo.setSelectedItem(nuevoprestamo.getTipoprestamo());
                                        tfinteres.setText(String.valueOf(nuevoprestamo.getInteres()));
                                        fechaprestamo.setDate(nuevoprestamo.getFechaprestamo());
                                        tfclienteprestamo.setText(nuevoprestamo.getNombrec());
                                        valorcuotas();
                                        
                                        tfcuotas.setEditable(true);
                                        tfinteres.setEditable(true);
                                        tfvalorprestamo.setEditable(true);
                                        fechaprestamo.setEnabled(true);
                                        
                                
                                }
                            }
                        break;
                    case "Eliminar prestamo":
                             codigoprestamo = tfbcprestamo.getText();
                        if (codigoprestamo.isEmpty() == true) {
                                JOptionPane.showMessageDialog(this, "Digite el codigo del prestamo a buscar");
                        }else{
                                Integer codigopres = null;
                                codigopres = new Integer(codigoprestamo);
                                nuevoprestamo = tbpres.Buscarprestamo(codigopres);
                                if (nuevoprestamo == null) {
                                    JOptionPane.showMessageDialog(this, "El prestamo con codigo " + codigopres+ " no existe");
                            }
                                tfvalorprestamo.setText(String.valueOf(nuevoprestamo.getValorprestamo()));
                                tfcuotas.setText(String.valueOf(nuevoprestamo.getNcuotas()));
                                cbtipoprestamo.setSelectedItem(nuevoprestamo.getTipoprestamo());
                                tfinteres.setText(String.valueOf(nuevoprestamo.getInteres()));
                                fechaprestamo.setDate(nuevoprestamo.getFechaprestamo());
                                tfclienteprestamo.setText(nuevoprestamo.getNombrec());
                                valorcuotas();
                        
                        }
                        
                        break;
                     case "Nuevo prestamo":
                            String cedulacliente = tfbcprestamo.getText();
                            if (cedulacliente.isEmpty()==true) {
                                JOptionPane.showMessageDialog(this,"Se requiere la cedula del cliente a buscar");
                         }else{
                                tbclientedatos nuevocliente = new tbclientedatos();
                                Tbcliente cliente = new Tbcliente();
                                Integer cedulac;
                                   cliente = nuevocliente.BuscarCliente( Integer.parseInt(cedulacliente));
                                   if (cliente == null) {
                                       JOptionPane.showMessageDialog(this,"El cliente con cedula"+" "+ cedulacliente+" no existe");
                                       
                                }else{
                                        tfclienteprestamo.setText(cliente.getNombres() +" "+ cliente.getApellidos());
                                        tfvalorprestamo.setEditable(true);
                                        tfinteres.setEditable(true);
                                        tfcuotas.setEditable(true);
                                        fechaprestamo.setEnabled(true);
                                        
                                   }
                                   
                            }
                        
                        break;
                    default:
                        throw new AssertionError();
                }
                
                
                
        } catch (Exception e) {
        }
        
        
        
        
    }//GEN-LAST:event_bbuscarcprestamoActionPerformed

    private void tfvalorprestamoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfvalorprestamoKeyTyped
      char c = evt.getKeyChar();
            if (c < '0' || c > '9') {
                evt.consume();
               JOptionPane.showMessageDialog(this, "Digite solo numeros");
        }
    }//GEN-LAST:event_tfvalorprestamoKeyTyped

    private void tfcuotasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcuotasKeyTyped
      char c = evt.getKeyChar();
            if (c < '0' || c > '9') {
                evt.consume();
               JOptionPane.showMessageDialog(this, "Digite solo numeros");
        }
    }//GEN-LAST:event_tfcuotasKeyTyped

    public void valorcuotas(){
     try {
            if (!tfinteres.getText().isEmpty()) {
                if (!tfcuotas.getText().isEmpty() && !tfvalorprestamo.getText().isEmpty()) {

                    Integer ncuotas, valorprestamo ;
                    Integer valorcuota;
                    float interes ;
                    interes = new Integer(tfinteres.getText());
                    interes = interes /100;
                    
                    System.out.println(interes);
                    ncuotas = Integer.parseInt(tfcuotas.getText());
                    valorprestamo = Integer.parseInt(tfvalorprestamo.getText());
                    valorcuota = Math.round((valorprestamo * interes + valorprestamo) / ncuotas);
                 
                    String valorcuotas = String.valueOf(valorcuota);
                    tfvalorcuota.setText(valorcuotas);

                }
            }

        } catch (Exception e) {
        }
    
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaprestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaprestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaprestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaprestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaprestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baceptarp;
    private javax.swing.JButton bbuscarcprestamo;
    private javax.swing.JButton bcancelar;
    private javax.swing.JButton blimpiarprestamo;
    private javax.swing.JComboBox<String> cbtipoprestamo;
    private com.toedter.calendar.JDateChooser fechaprestamo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbbcprestamo;
    private javax.swing.JLabel lbtituloprestamo;
    private javax.swing.JTextField tfbcprestamo;
    private javax.swing.JTextField tfclienteprestamo;
    private javax.swing.JTextField tfcuotas;
    private javax.swing.JTextField tfinteres;
    private javax.swing.JTextField tfvalorcuota;
    private javax.swing.JTextField tfvalorprestamo;
    // End of variables declaration//GEN-END:variables
}
