/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prestamos.ventanas;

import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import prestamos.controlador.TbclienteJpaController;
import prestamos.datos.tbclientedatos;
import prestamos.entity.Tbcliente;

/**
 *
 * @author Elisvan
 */

public class ventanaclientes extends javax.swing.JFrame {
 Tbcliente nuevocliente;
 public int sw = 0;
    /**
     * Creates new form ventanaclientes
     */
    public ventanaclientes() {
        initComponents();
    }

    public JTextField getTfcedulac() {
        return tfcedulac;
    }

    public int getSw() {
        return sw;
    }

    public void setSw(int sw) {
        this.sw = sw;
    }

    public JTextField getTfdireccionc() {
        return tfdireccionc;
    }

    public JTextField getTfnombrec() {
        return tfnombrec;
    }

    public JTextField getTftelefonoc() {
        return tftelefonoc;
    }
    

    ventanaclientes(JFrame jFrame, boolean b) {
       initComponents();
    }

    public void setBaggcliente(JButton baggcliente) {
        this.baggcliente = baggcliente;
    }

    public void setBbuscarc(JButton bbuscarc) {
        this.bbuscarc = bbuscarc;
    }

    public void setBeditarcliente(JButton beditarcliente) {
        this.beditarcliente = beditarcliente;
    }

    public void setBlimpiar(JButton blimpiar) {
        this.blimpiar = blimpiar;
    }

    public void setjButton2(JButton jButton2) {
        this.bcancelar = jButton2;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public void setTfcedulac(JTextField tfcedulac) {
        this.tfcedulac = tfcedulac;
    }

    public void setTfdireccionc(JTextField tfdireccionc) {
        this.tfdireccionc = tfdireccionc;
    }

    public void setTfnombrec(JTextField tfnombrec) {
        this.tfnombrec = tfnombrec;
    }

    public void setTftelefonoc(JTextField tftelefonoc) {
        this.tftelefonoc = tftelefonoc;
    }

   

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        baggcliente = new javax.swing.JButton();
        beditarcliente = new javax.swing.JButton();
        bcancelar = new javax.swing.JButton();
        tfcedulac = new javax.swing.JTextField();
        tfnombrec = new javax.swing.JTextField();
        tfdireccionc = new javax.swing.JTextField();
        blimpiar = new javax.swing.JButton();
        tftelefonoc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bbuscarc = new javax.swing.JButton();
        tfapellidosc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Informacion Cliente");

        jLabel2.setText("Cedula:");

        jLabel3.setText("Nombres:");

        jLabel4.setText("Direccion:");

        baggcliente.setText("Agregar");
        baggcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baggclienteActionPerformed(evt);
            }
        });

        beditarcliente.setText("Editar");
        beditarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditarclienteActionPerformed(evt);
            }
        });

        bcancelar.setText("Cancelar");
        bcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelarActionPerformed(evt);
            }
        });

        tfcedulac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcedulacActionPerformed(evt);
            }
        });
        tfcedulac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfcedulacKeyTyped(evt);
            }
        });

        tfnombrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnombrecActionPerformed(evt);
            }
        });

        tfdireccionc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdireccioncActionPerformed(evt);
            }
        });

        blimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/images_opt.jpg"))); // NOI18N
        blimpiar.setText("Limpiar");
        blimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blimpiarActionPerformed(evt);
            }
        });

        tftelefonoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftelefonocActionPerformed(evt);
            }
        });

        jLabel5.setText("Telefono:");

        bbuscarc.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        bbuscarc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconobuscar_opt (1).png"))); // NOI18N
        bbuscarc.setText("Buscar");
        bbuscarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbuscarcActionPerformed(evt);
            }
        });

        tfapellidosc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfapellidoscActionPerformed(evt);
            }
        });

        jLabel6.setText("Apellidos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfcedulac, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(bbuscarc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(blimpiar)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfnombrec, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfapellidosc, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfdireccionc)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tftelefonoc, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))
                        .addGap(14, 14, 14))))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(baggcliente)
                .addGap(35, 35, 35)
                .addComponent(beditarcliente)
                .addGap(55, 55, 55)
                .addComponent(bcancelar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfcedulac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bbuscarc)
                        .addComponent(blimpiar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfnombrec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfapellidosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdireccionc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tftelefonoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bcancelar)
                    .addComponent(beditarcliente)
                    .addComponent(baggcliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfnombrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnombrecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnombrecActionPerformed

    public JButton getBeditarcliente() {
        return beditarcliente;
    }

    public JButton getBaggcliente() {
        return baggcliente;
    }

    public JTextField getTfapellidosc() {
        return tfapellidosc;
    }

    public JButton getBbuscarc() {
        return bbuscarc;
    }

    public JButton getBlimpiar() {
        return blimpiar;
    }

    private void tfdireccioncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdireccioncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdireccioncActionPerformed

    private void bcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelarActionPerformed
           this.dispose();
    }//GEN-LAST:event_bcancelarActionPerformed

    private void tftelefonocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftelefonocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftelefonocActionPerformed

    private void bbuscarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbuscarcActionPerformed
      String cedulac = tfcedulac.getText();
       
        if (cedulac.isEmpty()== true) {
            JOptionPane.showMessageDialog(this, "Digite la cedula del cliente a buscar");
        }else{
               // EntityManagerFactory conexion = Persistence.createEntityManagerFactory("PrestamosPU");
                TbclienteJpaController clientebd = new TbclienteJpaController();
                tbclientedatos cliente = new tbclientedatos();
                Integer txtcedula = null;
                
                try {
                        txtcedula = new Integer(cedulac);
                        nuevocliente = clientebd.findTbcliente(txtcedula);
                    
                        if (nuevocliente == null) {
                             JOptionPane.showMessageDialog(this, "La cedula no se encontro");
                    }
                        else{
                                tfnombrec.setText(nuevocliente.getNombres());
                                tfapellidosc.setText(nuevocliente.getApellidos());
                                tfdireccionc.setText(nuevocliente.getDireccion());
                                tftelefonoc.setText(nuevocliente.getTelefono());
                                
                                tfnombrec.setEditable(true);
                                tfapellidosc.setEditable(true);
                                tfdireccionc.setEditable(true);
                                tftelefonoc.setEditable(true);
                     //   cliente
                        
                        }
                    
            } catch (Exception e) {
            }
        
        
        }
      
    }//GEN-LAST:event_bbuscarcActionPerformed

    private void beditarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditarclienteActionPerformed
        tbclientedatos cliente = new tbclientedatos();
       if (tfnombrec.getText().isEmpty() || tfapellidosc.getText().isEmpty() || tfcedulac.getText().isEmpty() || tfdireccionc.getText().isEmpty() || tftelefonoc.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Error ingrese todos los datos del cliente");
            }else{
                Integer cedula ;
                cedula = new Integer( tfcedulac.getText());
                 
                 System.out.println(cliente.mensaje);
                 cliente.Editarcliente(tfnombrec.getText(), tfapellidosc.getText(),Integer.parseInt(tfcedulac.getText()) , tfdireccionc.getText(), tftelefonoc.getText());
                  JOptionPane.showMessageDialog(this, cliente.mensaje);
            }
        
        
        
    }//GEN-LAST:event_beditarclienteActionPerformed

    private void baggclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baggclienteActionPerformed
     tbclientedatos ncliente = new tbclientedatos();
     
        if (baggcliente.getText().equals("Eliminar")) {
            try {
                Integer cedula ;
                cedula = new Integer( tfcedulac.getText());
                ncliente.Eliminarcliente(cedula);
                JOptionPane.showMessageDialog(this, ncliente.mensaje);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, ncliente.mensaje );
            }
            
            
        }else{
     
     
            try {
                if (tfnombrec.getText().isEmpty() || tfapellidosc.getText().isEmpty() || tfcedulac.getText().isEmpty() || tfdireccionc.getText().isEmpty() || tftelefonoc.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Error ingrese todos los datos del cliente");
                }else{
                    Integer cedula ;
                    cedula = new Integer( tfcedulac.getText());
                     ncliente.Agregarcliente(tfnombrec.getText(), tfapellidosc.getText(),cedula,tfdireccionc.getText(), tftelefonoc.getText());
                     System.out.println(ncliente.mensaje);
                      JOptionPane.showMessageDialog(this, ncliente.mensaje);
                }

            } catch (Exception e) {
                  JOptionPane.showMessageDialog(this, ncliente.mensaje);

            }
    }
     limpiar();   
    }//GEN-LAST:event_baggclienteActionPerformed
    private void limpiar(){
    tfapellidosc.setText(null);
    tfcedulac.setText(null);
    tfdireccionc.setText(null);
    tfnombrec.setText(null);
    tftelefonoc.setText(null);
    
    }
    private void blimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blimpiarActionPerformed
    
    limpiar();
            
    }//GEN-LAST:event_blimpiarActionPerformed

    private void tfcedulacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcedulacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcedulacActionPerformed

    private void tfapellidoscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfapellidoscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfapellidoscActionPerformed

    private void tfcedulacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcedulacKeyTyped
      char c = evt.getKeyChar();
            if (c < '0' || c > '9') {
                evt.consume();
               JOptionPane.showMessageDialog(this, "Digite solo numeros");
        }
    }//GEN-LAST:event_tfcedulacKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaclientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaclientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaclientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaclientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaclientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baggcliente;
    private javax.swing.JButton bbuscarc;
    private javax.swing.JButton bcancelar;
    private javax.swing.JButton beditarcliente;
    private javax.swing.JButton blimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tfapellidosc;
    private javax.swing.JTextField tfcedulac;
    private javax.swing.JTextField tfdireccionc;
    private javax.swing.JTextField tfnombrec;
    private javax.swing.JTextField tftelefonoc;
    // End of variables declaration//GEN-END:variables
}
