/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prestamos.ventanas;

import com.toedter.calendar.JCalendar;
import com.toedter.calendar.JDateChooser;
import java.util.Calendar;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import prestamos.datos.tbpagosdatos;
import prestamos.datos.tbprestamosdatos;
import prestamos.entity.Tbpagos;
import prestamos.entity.Tbprestamo;

/**
 *
 * @author Elisvan
 */
public class ventanapagos extends javax.swing.JFrame {

    Tbprestamo prestamo;
    Tbpagos pago;

    public ventanapagos() {
        initComponents();
    }

    public JDateChooser getFechapago() {
        return fechapago;
    }

    public void setFechapago(JDateChooser fechapago) {
        this.fechapago = fechapago;
    }

    public JLabel getLbcuotaspendientes() {
        return lbcuotaspendientes;
    }

    public void setLbcuotaspendientes(JLabel lbcuotaspendientes) {
        this.lbcuotaspendientes = lbcuotaspendientes;
    }

    public JLabel getLbsaldoactual() {
        return lbsaldoactual;
    }

    public void setLbsaldoactual(JLabel lbsaldoactual) {
        this.lbsaldoactual = lbsaldoactual;
    }

    public JLabel getLbvalortotalpagar() {
        return lbvalortotalpagar;
    }

    public void setLbvalortotalpagar(JLabel lbvalortotalpagar) {
        this.lbvalortotalpagar = lbvalortotalpagar;
    }

    public JLabel getLbvcuota() {
        return lbvcuota;
    }

    public void setLbvcuota(JLabel lbvcuota) {
        this.lbvcuota = lbvcuota;
    }

    public JTextField getTfcuotaspagar() {
        return tfcuotaspagar;
    }

    public void setTfcuotaspagar(JTextField tfcuotaspagar) {
        this.tfcuotaspagar = tfcuotaspagar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfbprest = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbvcuota = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbsaldoactual = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbcuotaspendientes = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfcuotaspagar = new javax.swing.JTextField();
        lbncliente = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fechapago = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        lbvalortotalpagar = new javax.swing.JLabel();
        btaceptarp = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Realizar pago:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Buscar prestamo:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconobuscar_opt (1).png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Nombre cliente:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Valor cuota:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Saldo actual:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("#cuotas pendientes");

        lbcuotaspendientes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("#Cuotas a pagar:");

        tfcuotaspagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcuotaspagarActionPerformed(evt);
            }
        });
        tfcuotaspagar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfcuotaspagarKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Fecha de pago");

        fechapago.setDateFormatString("yyyy/MM/d");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Valor total a pagar");

        btaceptarp.setText("Aceptar");
        btaceptarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaceptarpActionPerformed(evt);
            }
        });

        btcancelar.setText("Cancelar");
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel8)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbvcuota, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbsaldoactual, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbcuotaspendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(tfcuotaspagar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbvalortotalpagar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btcancelar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbncliente, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfbprest, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btaceptarp)
                    .addComponent(fechapago, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfbprest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbncliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbcuotaspendientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbvcuota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfcuotaspagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbsaldoactual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(fechapago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(lbvalortotalpagar, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btaceptarp)
                    .addComponent(btcancelar))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String codigoprestamo = tfbprest.getText();
        tbprestamosdatos tbpres = new tbprestamosdatos();
        if (codigoprestamo.isEmpty() == true) {
            JOptionPane.showMessageDialog(this, "Digite el codigo del prestamo a buscar");
        } else {
            Integer codigopres = null;
            codigopres = new Integer(codigoprestamo);
            prestamo = tbpres.Buscarprestamo(codigopres);
            if (prestamo == null) {
                JOptionPane.showMessageDialog(this, "El prestamo con codigo " + codigopres + " no existe");
            } else {
                lbsaldoactual.setText(String.valueOf(prestamo.getNcuotas() * prestamo.getValorcuota()));
                lbcuotaspendientes.setText(String.valueOf(prestamo.getNcuotas()));

                //fechapago.setDate(prestamo.getFechaprestamo());
                lbncliente.setText(prestamo.getNombrec());
                lbvcuota.setText(String.valueOf(prestamo.getValorcuota()));
                tfcuotaspagar.setEditable(true);
            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfcuotaspagarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcuotaspagarKeyReleased
        try {
            if (!tfcuotaspagar.getText().isEmpty() && !lbvcuota.getText().isEmpty()) {
                if (Integer.parseInt(lbcuotaspendientes.getText()) < Integer.parseInt(tfcuotaspagar.getText())) {
                    JOptionPane.showMessageDialog(this, "Digite un numero valido de cuotas a pagar");
                } else {
                    Integer totalpagar = Integer.parseInt(tfcuotaspagar.getText()) * Integer.parseInt(lbvcuota.getText());
                    lbvalortotalpagar.setText(totalpagar + "");
                    btaceptarp.setEnabled(true);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Digite solo numeros");
        }

    }//GEN-LAST:event_tfcuotaspagarKeyReleased

    public JButton getBtaceptarp() {
        return btaceptarp;
    }

    public void setBtaceptarp(JButton btaceptarp) {
        this.btaceptarp = btaceptarp;
    }

    private void btaceptarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaceptarpActionPerformed
        tbprestamosdatos prest = new tbprestamosdatos();
        tbpagosdatos pagosdatos = new tbpagosdatos();
        ventanaprestamos vprest = new ventanaprestamos();
        JCalendar fechavencerc = fechapago.getJCalendar();
        String cbprestamo = prestamo.getTipoprestamo();
        switch (cbprestamo) {
            case "Diario":

                Calendar fpres = fechapago.getCalendar();
                fpres.add(Calendar.DATE, 1);

                fechavencerc.setCalendar(fpres);

                break;
            case "Semanal":
                fpres = fechapago.getCalendar();
                fpres.add(Calendar.DATE, 7);
                fechavencerc.setCalendar(fpres);

                break;
            case "Quincenal":
                fpres = fechapago.getCalendar();
                fpres.add(Calendar.DATE, 15);
                fechavencerc.setCalendar(fpres);

                break;
            case "Mensual":
                fpres = fechapago.getCalendar();
                fpres.add(Calendar.DATE, 30);
                fechavencerc.setCalendar(fpres);

                break;
            default:

        }
       
        Integer cuotaspendientes = Integer.parseInt(lbcuotaspendientes.getText()) - Integer.parseInt(tfcuotaspagar.getText());
        prest.Editarprestamo(prestamo.getCodigo(),prestamo.getNombrec(),prestamo.getValorprestamo(), cuotaspendientes, prestamo.getInteres(), prestamo.getTipoprestamo(), prestamo.getValorcuota(), prestamo.getFechaprestamo(), fechavencerc.getDate());
        if (cuotaspendientes == 0) {
            
            int resp = JOptionPane.showConfirmDialog(this, "¿Si realiza el pago quedarian 0 cuotas pendientes, ¿desea eliminar el prestamo??", "Notificacion!", JOptionPane.YES_NO_OPTION);
            if (resp == 0) {
                try {
                    prest.Eliminarprestamo(Integer.parseInt(tfbprest.getText()));
                    JOptionPane.showMessageDialog(this, prest.mensaje);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error al eliminar");
                }

            }
        }
       Integer sactual = Integer.parseInt(lbsaldoactual.getText()) - Integer.parseInt(lbvcuota.getText()) * Integer.parseInt(tfcuotaspagar.getText());
        pagosdatos.Realizarpago(Integer.parseInt(tfbprest.getText()),lbncliente.getText(), sactual, Integer.parseInt(tfcuotaspagar.getText()), cuotaspendientes, fechapago.getDate());
        JOptionPane.showMessageDialog(this, pagosdatos.mensaje);
        limpiar();

    }//GEN-LAST:event_btaceptarpActionPerformed
   public void limpiar(){
   tfbprest.setText(null);
   lbncliente.setText(null);
   lbvcuota.setText(null);
   lbsaldoactual.setText(null);
   fechapago.setDate(null);
   lbcuotaspendientes.setText(null);
   tfcuotaspagar.setText(null);
   lbvalortotalpagar.setText(null);
   
   
   }
    private void tfcuotaspagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcuotaspagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcuotaspagarActionPerformed

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
     this.dispose();
    }//GEN-LAST:event_btcancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanapagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanapagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanapagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanapagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanapagos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btaceptarp;
    private javax.swing.JButton btcancelar;
    private com.toedter.calendar.JDateChooser fechapago;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbcuotaspendientes;
    private javax.swing.JLabel lbncliente;
    private javax.swing.JLabel lbsaldoactual;
    private javax.swing.JLabel lbvalortotalpagar;
    private javax.swing.JLabel lbvcuota;
    private javax.swing.JTextField tfbprest;
    private javax.swing.JTextField tfcuotaspagar;
    // End of variables declaration//GEN-END:variables

}
